# The internal git client reads CIRRUS_CLONE_DEPTH.
env:
  CIRRUS_CLONE_DEPTH: 3
  MAKEFLAGS: '-j 2'
  IGNORE_OSVERSION: yes

task:
  freebsd_instance:
    image_family: freebsd-$OSREL
  env:
    matrix:
      - OSREL: 11-4
      - OSREL: 12-2
      - OSREL: 13-0-snap
  script:
    - freebsd-version
    - pkg install -qy autoconf
    - touch .devel
    - ./configure --enable-remote --prefix=/tmp
    - make -s all
    - make -s testprogs
    - make install
    - make releasetar
    - testprogs/findalldevstest
